### ISSUE TITLE
Update action URLs to fix nonce collisions  

### ISSUE THREAD

**Issue by williamsba** [WebDevStudios/CollabPress#27]
Generated URLs for actions (edit/delete task, complete task, etc) are created as a variable with querystring and nonce values added.  The problem with this approach is the nonce values stay in the URLs after an action is completed causing collisions.  

Steps to reproduce:
1.  Complete an active task
2.  Create a new task

You'll see a "Are you sure you want to do this?" message because it's checking the wrong nonce value.

To fix we need to complete the following updates:
1.  Use add_query_arg() to generate the action URLs
2.  Process the data before headers are sent
3.  Use wp_redirect() to redirect back to the proper screen, thus removing the nonce values from the querystring

You can see an example of the code that needs updated here:
https://github.com/WebDevStudios/CollabPress/blob/master/includes/functions.php#L732

**Comment by ericandrewlewis** [comment]
In 1.3 I'm thinking that all actions will be completed via ajax calls and then javascript redirects/refreshes, instead of the action URL and redirect method. This will keep us moving towards a goal of MV\* (haven't picked a framework yet). 

With this method, we should be able to respond with a fresh nonce from the AJAX request, and use that for the next request, repeat.

**Comment by williamsba** [comment]
That sounds like a good plan to me.  That would eliminate the current methods we are using and fix this issue.

**Comment by ericandrewlewis** [comment]
In e05f5d348383931d0a86c8e34658e56806086c90, nonces added into the AJAX requests for all administrative actions in CollabPress.
