### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by HeleneFi** [WebDevStudios/CollabPress#67]
Hi, I uploaded the update 1.3.1.1, many of the bugs are fixed. Some of them remain and it seems something that was a critical feature disapeared. So here's the list of what remains by order of importance:

Links and attachments This is critical for effective work!
1. Can't have html in description, so can't link to other pages such as docs or embed multimedia via iframes etc...? I remember this was possible in the earlier release... not sure... (NEW ISSUE)
2. Can't upload and access files, project overview and activity (front end group view). Project related files and attachments accessible via groups are critical.

Tasks & task assignments
3. There are no dates on task comments (all)
4. Tasks have no names? Only descriptions that are displayed as a name. Might explain the issue of alignment... (nothing next to the bullet points in front end group view.)
5. Task lists don't work: no link to open it (all levels) (NEW ISSUE DETECTED)
6.  Email notification of task assignment arrives as “You have been assigned the task 0″ (0 instead of task name…) (all levels)
7. Assignments made to tasks at the group level are not 'kept'/transferred at general level, automatically changes to the current user identified by user name and not actual name (my user name is 'admim' so I can't quite analyze what is going on here exactly) with no appearance of initial assignees in the assignment box. So if someone is a member of multiple groups and wants to deal with tasks at the general or back end level, he can mess things up without knowing it...
8. It seems that there is no option in the general level/backend to assign tasks to other people than oneself...
9. Can't assign several people to a task (no multiple selection in selection box…) So can't create a task or project team or distribution list...  (all). That would be cool to have.

Email notification
10. Email notification checkbox ignored (email sent even if unchecked when email is enabled in settings, and not sent even if checked when email is disabled in settings)  (all)

Display & Layout
11. No "back to project" option in task once comments are finished or or "back" or "cancel" option when editing (all) not a problem when project overview is accessible, a problem on group view... where there are no project related tabs to remain in the same work perimeter see pt 3
12. Little icons missing on group sidebar nav for projects & calendar. See http://commonsabundance.net/groups/test-group/projects/
13. Image to upload to replace the grey square on projects page?
14. Center project title in square?

**Comment by ericandrewlewis** [comment]
Hi Helene,

I've opened #68 for HTML in task comments. We've never allowed HTML in either task descriptions or comments before, the latter being an easy fix, the prior requiring some more forethought. 

I opened #49 a while ago to track BuddyPress feature parity. This is not a new issue, as these features have never been ported over to the BuddyPress integration. 

I've opened #69 for dates in the task comments template.

I haven't seen an issue with the description of a task not showing up in the BuddyPress template. The description and the name of a task are synonymous here.

Task lists don't have devoted pages in CollabPress 1.3, since you can see a nested view of all task lists at the project level. However I'd like to see this feature added in a future version, I've opened #70.

Opened #71 for task names output as "0" in emails.

I'm not sure what you mean about assignments not "keeping" between the group and general level. BuddyPress and the "general" CollabPress areas are not intended to overlap at all out-of-the-box.

Email notifications should have been fixed in #57.

There is a breadcrumb that gives you a link back to the project in the BuddyPress template.

The sidebar icons are custom-made by your theme, which we can't support from the plugin.

The CollabPress templates are completely customizable by coping the template folder from includes/templates/collabpress/ into the root of your theme and modifying there. 

Thanks again for your great testing and bug reports. If any more come up, or you have response to any of these in particular please open up separate Github issues here, I'm going to close this thread.

**Comment by HeleneFi** [comment]
More critical than html in task description is html in Project description. My first points are related to HTML in Project description. Hope this was clear.

**Comment by ericandrewlewis** [comment]
Ah, didn't catch that. Sure thing, opening #73 for that, and putting it on the 1.4 milestone.

**Comment by HeleneFi** [comment]
Oops I opened one for this at the same time, so closed it :)

**Comment by HeleneFi** [comment]
Some clarification on your comments and questions: 

"I haven't seen an issue with the description of a task not showing up in the BuddyPress template. The description and the name of a task are synonymous here."

It really seems like the name entry box is missing in the create/edit task window. If you compare the project and task create/edit, it is clear... 
In display of task mode at the front end level (that I can't show you now because there's a pb with BP 1.7 it seems...) it's even clearer. You have a bullet with nothing next to it, and the description comes underneath...

Anyway, however it was conceived in the first place. Tasks need a name AND a description.

**Comment by HeleneFi** [comment]
"I'm not sure what you mean about assignments not "keeping" between the group and general level. BuddyPress and the "general" CollabPress areas are not intended to overlap at all out-of-the-box."

OK not sure what it means here. let me take a concrete example:
I created a task that I assigned to myself. On the front end level, it appeared under my actual name. When visualizing it at the collabpress dashboard level it appeared assigned to 'admin' which is my username. I can't get to reproduce this because it seems BP 1.7 (or Cbox 1.04) is incompatible with collabpress so I can't create/ visualize projects and tasks anymore... But it seemed to me that the front end and back end of collabpress do not behave similarly.

One thing important to note is that as a COLLABORATION FACILITATION TOOL, collab press is by definition something that must be most effective front end at the USER/UI level, because this is where people are meant to collaborate, schedule, achieve, accomplish tasks in a coordinated manner. So any specific collaboration feature that is only accessible via the dashboard is not actually useful!

**Comment by ericandrewlewis** [comment]
Regarding tasks not having a description and name: 

Tasks by their nature have a name and then a conversation on it. I don't see a reason why tasks need a description that would be separate from the conversation in the comments. Nonetheless, if you'd like to open this discussion more, please open a new issue for it.

Regarding differences between front-end and back-end:

The admin interface version of CollabPress and the front-end version of CollabPress both use the same templates. The BuddyPress version of CollabPress uses separate templates, which may be where you're seeing minute differences between the output of usernames vs. display names. BP 1.7 and Cbox 1.04 should both be compatible with CollabPress; if there are any specific bugs please open up new bug reports as issues here

For any follow-up on topics here, please open up new issues so the topics can be discussed distinctly and archived for the future in a categorized manner. Thanks!

**Comment by HeleneFi** [comment]
OK thxs, & sorry for any clumsyness. I'm not 100% familiar with front/end back end terminology and how various plugins 'integrate' with each other. From a user perspective with a BP social network, I'd like collabpress features to be accessible in full via my BP UI... (or wathever interface my users are interacting with).
